name: Test Matrix
on:
  push:
    branches:
      - master
  pull_request:
    branches: ["*"]

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: install python deps
        run: pip3 install tox tox-docker
      - name: run tests
        run: tox -e py$(echo ${{ matrix.py }} | tr -d .)

  postgres:
    name: Postgresql
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg: [12, 13, 14, 15]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install python deps
        run: pip3 install tox tox-docker
      - name: run tests
        run: tox -e py310-pg${{ matrix.pg }}

  contrib:
    name: Contrib
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg: [vector]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install python deps
        run: pip3 install tox tox-docker
      - name: run tests
        run: tox -e ${{ matrix.pg }}

  psycopg2.8:
    name: psycopg2.8
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install python deps
        run: pip3 install tox tox-docker
      - name: run tests
        run: tox -e psycopg2.8
